name: Downgrade
on:
  pull_request:
    branches: [master, main]
    paths-ignore:
      - 'docs/**'
  push:
    branches: [master, main]
    paths-ignore:
      - 'docs/**'
env:
  PYTHON: ~
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.10']
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: cjdoris/julia-downgrade-compat-action@v1
        with:
          skip: Pkg,TOML,InteractiveUtils,Random,LinearAlgebra

      - name: Full Pkg Operations
        run: |
          julia -e '
          import Pkg

          try
              Pkg.Registry.rm("General")
          catch e
              @warn "Failed to remove General registry: $e"
          end
          Pkg.Registry.add("General")
          Pkg.Registry.update()

          @info "Pkg.Registry.status() output:"
          println(Pkg.Registry.status())
          @info "Checking QuantumSavory in registry status:"
          try
              Pkg.Registry.status("QuantumSavory")
          catch e
              @error "Failed to get status for QuantumSavory from registry: $e"
          end

          Pkg.activate(".")
          try
              Pkg.instantiate()
          catch e
              @error "Failed to instantiate root project!" exception=(e, catch_backtrace())
              rethrow(e)
          end

          Pkg.activate("test")
          try
              Pkg.instantiate()
          catch e
              @error "Failed to instantiate test environment!" exception=(e, catch_backtrace())
              rethrow(e)
          end

          test_pkg_list = Pkg.installed()
          if "QuantumSavory" in keys(test_pkg_list)
              @info "QuantumSavory found in test environment: $(test_pkg_list["QuantumSavory"].version)"
          else
              @error "QuantumSavory NOT found in test environment after instantiation."
              error("Critical: QuantumSavory not found.")
          end

          Pkg.build()
          Pkg.test("QuantumSymbolics"; coverage=true) # No JULIA_NUM_THREADS matrix for downgrade.yml
          ' 
